config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :articles do
    resources :comments, only:[:create,:destroy,:update]
  end
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/dashboard", to: "welcome#dashboard"

  put "/articles/:id/publish",to: "articles#publish"
end

app/models/article.rb
class Article < ApplicationRecord

  include AASM

  belongs_to :user
  has_many :comments
  has_many :has_categories
  has_many :categories, through: :has_categories
  attr_reader :categories
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: {minimum: 20}
  before_save :set_visits_count
  after_create :save_categories

  has_attached_file :cover, style:{medium:"1280x720",thumb:"400x200"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  #scope para parametros / pueden ser encadenables
  #scope :publicados, ->{where(state: "published")}

  def categories=(value)
    @categories=value
  end
  def update_visits_count
    self.save if self.visits_count.nil?
    self.update(visits_count: self.visits_count + 1)
  end
  aasm_column :state
  aasm do
    state :in_draft,:initial=> true
    state :published

    event :publish do
      transitions :form=> :in_draft, :to=> :published
    end
    event :unpublish do
      transitions :form=> :published, :to=> :in_draft
    end
  end

  private
  def set_visits_count
    self.visits_count ||= 0
  end
  def save_categories
    @categories.each do |category_id|
      HasCategory.create(category_id: category_id,article_id: self.id)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :set_article, except: [:index,:new,:create]
  before_action :authenticate_editor!,only: [:new,:create,:update]
  before_action :authenticate_admin!,only: [:destroy,:publish]
  def index
    @article=Article.paginate(page: params[:page],per_page:4).published
  end
  def show
    @article.update_visits_count
    @comment=Comment.new
  end
  def new
    @article=Article.new
    @categories =Category.all
  end
  def create
    @article=current_user.articles.new(article_params)
    @article.categories =params[:categories]
   if @article.save
    redirect_to @article
   else
     render :new
   end
  end
  def edit
  end
  def update
    if@article.update(article_params)
      redirect_to @article
    else
      render :'articles/edit'
    end
  end
  def publish
    @article.publish!
    redirect_to @article
  end
  def destroy
    @article.destroy
    redirect_to root_path
  end
  private
  def article_params
    params.require(:article).permit(:title,:body,:cover,:categories)
  end
  def set_article
    @article=Article.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<h1><%= name%> Articulo</h1>
<%= form_for(@article) do|f|%>
    <% @article.errors.full_messages.each do |message|%>
        <div class="be-red white top-space">
          *<%= message%>
        </div>
    <%end%>
    <div class="field">
      <%= f.text_field :title, placeholder:"Titulo",class:"form-control"%>
    </div>
    <div class="field">
      Portada <%= f.file_field :cover %>
    </div>
    <div class="field">
      <%=# f.text_area :body, placeholder:"Escribe aqui tu articulo",style:"display:none" ,class:"form-control"%>
    </div>
    <div id="epiceditor", style="height: 250px;">
    </div>
    <div class="field">
      <label>Categorias</label>
      <% @categories.each do |category| %>
          <div class="field">
            <%= check_box_tag "categories[]" ,category.id %> <%= category.name %>
          </div>
      <%end%>
    </div>
    <div class="field">
      <%=f.submit"Guardar Cambios",class:"btn" %>
    </div>
<%end%>
<!--<script>-->
//  var editor=new EpicEditor().load();
<!--</script>-->

app/views/articles/edit.html.erb
<div style="width: 80%;margin:0 auto;">
  <%= render 'articles/form',name:"Editar"%>

</div>

app/views/articles/index.html.erb
<h1>Articulos</h1>
<div class="row">
  <% @article.each do |article|%>
      <div class="col-md-4">
        <div class="box relative article-height">
          <div class="absolute article-height background-cover" style="background:url(<%= article.cover.url(:thumb)%>);top:0px;left:0px;width:100%;">
            <h2><%= link_to article.title, article%> </h2>
            <p>
              <%= truncate(article.body,length:20) %>
            </p>
          </div>
        </div>
      </div>
  <%end%>
</div>

<%= will_paginate @article %>

app/views/articles/new.html.erb
<div style="width: 80%;margin:0 auto;">
    <%= render 'articles/form',name:"Nuevo"%>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
  <%= @article.body%>
</div>
  <% unless @article.user.nil? %>
    <p>
      Escrito por: <%= @article.user.email %>
    </p>
  <%end%>
<div class="field">
  <%= image_tag @article.cover.url() %>
</div>
<p>Visitas: <%= @article.visits_count%></p>

<div>
  <%= link_to "Editar", edit_article_path(@article)%>
</div>
<div class="field">
  <h4>Comentarios</h4>
  <%= render "comments/form" %>
  <ul>
    <% @article.comments.each do |comments|%>
    <li>
      <%=comments.body%> - <%= comments.user.email  %>
    </li>

    <% end %>
  </ul>
</div>